// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcrXXb3FRhm3NoqMKZzGgn5diUUS1OpVM',
    appId: '1:416828681057:web:d5e2fb07d61966bf887320',
    messagingSenderId: '416828681057',
    projectId: 'wellbot-e8027',
    authDomain: 'wellbot-e8027.firebaseapp.com',
    storageBucket: 'wellbot-e8027.firebasestorage.app',
    measurementId: 'G-1EPBC1YPY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCugSEzb-kbs2lDrCHGK_TESqAfGZDVH8o',
    appId: '1:416828681057:android:0ef3bd23c7f2bd4a887320',
    messagingSenderId: '416828681057',
    projectId: 'wellbot-e8027',
    storageBucket: 'wellbot-e8027.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpC2KZePKWpEI9-Xxuk1EvKzp1Walm0r0',
    appId: '1:416828681057:ios:96fcbf1fdf687b53887320',
    messagingSenderId: '416828681057',
    projectId: 'wellbot-e8027',
    storageBucket: 'wellbot-e8027.firebasestorage.app',
    iosBundleId: 'com.example.wellbotapp',
  );
}
